// Traducciones de la web. Clave = texto en español tal cual aparece. [CA, EN, FR]
const T = [
['SUSHI · BUFFET LIBRE','SUSHI · BUFET LLIURE','SUSHI · ALL YOU CAN EAT','SUSHI · BUFFET À VOLONTÉ'],
['Precios','Preus','Prices','Tarifs'],['Galería','Galeria','Gallery','Galerie'],['Opiniones','Opinions','Reviews','Avis'],['Grupos','Grups','Groups','Groupes'],['Ubicación','Ubicació','Location','Accès'],
['CARTA','CARTA','MENU','CARTE'],['RESERVAR','RESERVAR','BOOK','RÉSERVER'],
['食べ放題 · BUFFET LIBRE','食べ放題 · BUFET LLIURE','食べ放題 · ALL YOU CAN EAT','食べ放題 · À VOLONTÉ'],
['¡Sushi sin','Sushi sense','Sushi with','Sushi sans'],['límites!','límits!','no limits!','limites !'],
['Buffet libre de cocina japonesa en un local lleno de anime: murales, figuras a tamaño real y neones. Pide lo que quieras, tantas veces como quieras.','Bufet lliure de cuina japonesa en un local ple d’anime: murals, figures a mida real i neons. Demana el que vulguis, tantes vegades com vulguis.','All-you-can-eat Japanese food in a place packed with anime: murals, life-size figures and neon. Order anything you like, as many times as you like.','Buffet japonais à volonté dans un lieu rempli d’anime : fresques, figurines grandeur nature et néons. Commandez ce que vous voulez, autant de fois que vous voulez.'],
['DESDE','DES DE','FROM','DÈS'],['RESERVAR MESA','RESERVAR TAULA','BOOK A TABLE','RÉSERVER UNE TABLE'],['VER CARTA','VEURE CARTA','SEE MENU','VOIR LA CARTE'],
['Rondas ilimitadas','Rondes il·limitades','Unlimited rounds','Tournées illimitées'],['Precio niños','Preu nens','Kids’ price','Tarif enfants'],['4,5 en Google','4,5 a Google','4.5 on Google','4,5 sur Google'],
['¡Come todo lo que quieras!','Menja tot el que vulguis!','Eat all you want!','Mangez à volonté !'],['¡Sushi','Sushi','Sushi','Sushi'],['sin','sense','with no','sans'],
['Buffet libre japonés con murales anime, figuras a tamaño real y neones. Salou, a dos calles de la playa.','Bufet lliure japonès amb murals anime, figures a mida real i neons. Salou, a dos carrers de la platja.','Japanese all-you-can-eat with anime murals, life-size figures and neon. Salou, two streets from the beach.','Buffet japonais à volonté avec fresques anime, figurines grandeur nature et néons. Salou, à deux rues de la plage.'],
['BUFFET LIBRE JAPONÉS · SALOU','BUFET LLIURE JAPONÈS · SALOU','JAPANESE ALL YOU CAN EAT · SALOU','BUFFET JAPONAIS À VOLONTÉ · SALOU'],['Sushi','Sushi','Sushi','Sushi'],['sin límites','sense límits','with no limits','sans limites'],
['Un homenaje al maestro del grabado japonés, servido en rondas infinitas. Cocina japonesa, murales de manga y la luz de los neones.','Un homenatge al mestre del gravat japonès, servit en rondes infinites. Cuina japonesa, murals de manga i la llum dels neons.','A tribute to the master of Japanese woodblock prints, served in endless rounds. Japanese food, manga murals and neon light.','Un hommage au maître de l’estampe japonaise, servi en tournées infinies. Cuisine japonaise, fresques manga et lumière des néons.'],
['システム · CÓMO FUNCIONA','システム · COM FUNCIONA','システム · HOW IT WORKS','システム · COMMENT ÇA MARCHE'],['Cuatro viñetas','Quatre vinyetes','Four panels','Quatre cases'],['y a comer','i a menjar','and let’s eat','et à table'],
['Siéntate','Seu','Sit down','Installez-vous'],['Te damos mesa y te contamos cómo va el buffet en un minuto.','Et donem taula i t’expliquem com funciona el bufet en un minut.','We seat you and explain the buffet in a minute.','On vous installe et on vous explique le buffet en une minute.'],
['Pide','Demana','Order','Commandez'],['Elige de la carta por rondas: nigiris, makis, woks, ramen… todo se prepara al momento.','Tria de la carta per rondes: nigiris, makis, woks, ramen… tot es prepara al moment.','Pick from the menu in rounds: nigiri, maki, wok, ramen… all made to order.','Choisissez sur la carte par tournées : nigiris, makis, woks, ramen… tout est préparé minute.'],
['Repite','Repeteix','Repeat','Recommencez'],['¿Te has quedado con ganas? Otra ronda. Y otra. Sin límite.','T’has quedat amb ganes? Una altra ronda. I una altra. Sense límit.','Still hungry? Another round. And another. No limit.','Encore faim ? Une autre tournée. Et encore une. Sans limite.'],
['Disfruta','Gaudeix','Enjoy','Profitez'],['Postre, fotos con las figuras y los neones. Aquí la sobremesa también cuenta.','Postres, fotos amb les figures i els neons. Aquí la sobretaula també compta.','Dessert, photos with the figures and the neon. Lingering after dinner counts here too.','Dessert, photos avec les figurines et les néons. Ici, on prend le temps après le repas.'],
['Normas de la casa','Normes de la casa','House rules','Règles de la maison'],['Precio por persona. Bebidas aparte.','Preu per persona. Begudes a part.','Price per person. Drinks not included.','Prix par personne. Boissons en supplément.'],
['Servicio rápido: cada ronda llega a tu mesa en un momento.','Servei ràpid: cada ronda arriba a la taula en un moment.','Fast service: every round reaches your table in no time.','Service rapide : chaque tournée arrive à table en un instant.'],
['Pide con cabeza: la comida que sobra se cobra aparte.','Demana amb seny: el menjar que sobra es cobra a part.','Order wisely: leftover food is charged separately.','Commandez raisonnablement : les restes sont facturés à part.'],
['Toda la mesa comparte la misma modalidad de buffet.','Tota la taula comparteix la mateixa modalitat de bufet.','The whole table shares the same buffet option.','Toute la table choisit la même formule.'],
['ネダン · PRECIOS','ネダン · PREUS','ネダン · PRICES','ネダン · TARIFS'],['Un precio.','Un preu.','One price.','Un prix.'],['Rondas infinitas.','Rondes infinites.','Endless rounds.','Tournées infinies.'],
['Mediodía','Migdia','Lunch','Midi'],['Lunes a viernes · 12:30–16:30','Dilluns a divendres · 12:30–16:30','Monday to Friday · 12:30–16:30','Lundi au vendredi · 12h30–16h30'],['ADULTO','ADULT','ADULT','ADULTE'],['NIÑO DE 3 A 8 AÑOS','NEN DE 3 A 8 ANYS','CHILD AGED 3 TO 8','ENFANT DE 3 À 8 ANS'],
['Noche y fin de semana','Nit i cap de setmana','Dinner & weekends','Soir et week-end'],['Todas las noches · sábado y domingo todo el día','Totes les nits · dissabte i diumenge tot el dia','Every evening · all day Saturday and Sunday','Tous les soirs · samedi et dimanche toute la journée'],
['Precio por persona, IVA incluido. Bebidas aparte.','Preu per persona, IVA inclòs. Begudes a part.','Price per person, VAT included. Drinks not included.','Prix par personne, TVA incluse. Boissons en supplément.'],
['メニュー · LA CARTA','メニュー · LA CARTA','メニュー · THE MENU','メニュー · LA CARTE'],['Todo esto,','Tot això,','All of this,','Tout ça,'],['sin límite','sense límit','no limit','sans limite'],['Mirar carta completa','Veure la carta completa','See full menu','Voir la carte complète'],
['Ocultar platos con:','Amagar plats amb:','Hide dishes with:','Masquer les plats avec :'],['Quitar filtros','Treure filtres','Clear filters','Effacer les filtres'],
['Ningún plato de esta sección está libre de los alérgenos que has marcado.','Cap plat d’aquesta secció està lliure dels al·lèrgens que has marcat.','No dish in this section is free of the allergens you selected.','Aucun plat de cette section n’est exempt des allergènes choisis.'],
['Alérgenos según la carta oficial. Si tienes alguna alergia o intolerancia, avisa al camarero.','Al·lèrgens segons la carta oficial. Si tens alguna al·lèrgia o intolerància, avisa el cambrer.','Allergens as listed on the official menu. If you have an allergy or intolerance, tell your waiter.','Allergènes selon la carte officielle. En cas d’allergie ou d’intolérance, prévenez le serveur.'],
['Nigiri','Nigiri','Nigiri','Nigiri'],['Makis, rolls y poke','Makis, rolls i poke','Maki, rolls & poke','Makis, rolls et poke'],['Sashimi y tataki','Sashimi i tataki','Sashimi & tataki','Sashimi et tataki'],['Arroces y fideos','Arrossos i fideus','Rice & noodles','Riz et nouilles'],['Gyozas y bao','Gyozas i bao','Gyoza & bao','Gyozas et bao'],['Entrantes calientes','Entrants calents','Hot starters','Entrées chaudes'],['Entrantes fríos','Entrants freds','Cold starters','Entrées froides'],['Postres','Postres','Desserts','Desserts'],
['Gluten','Gluten','Gluten','Gluten'],['Marisco','Marisc','Shellfish','Crustacés'],['Pescado','Peix','Fish','Poisson'],['Lácteos','Lactis','Dairy','Lait'],['Huevo','Ou','Egg','Œuf'],['Frutos secos','Fruits secs','Nuts','Fruits à coque'],['Sésamo','Sèsam','Sesame','Sésame'],['Soja','Soja','Soy','Soja'],['Moluscos','Mol·luscs','Molluscs','Mollusques'],['Mostaza','Mostassa','Mustard','Moutarde'],['Picante','Picant','Spicy','Épicé'],['Sin alérgenos declarados','Sense al·lèrgens declarats','No declared allergens','Sans allergène déclaré'],
['セカイ · LA EXPERIENCIA','セカイ · L’EXPERIÈNCIA','セカイ · THE EXPERIENCE','セカイ · L’EXPÉRIENCE'],['Cenar dentro','Sopar dins','Dine inside','Dîner dans'],['de un','d’un','a','un'],
['Noren a la entrada, murales pintados a mano, figuras a tamaño real y neones por todo el local. Trae el móvil cargado.','Noren a l’entrada, murals pintats a mà, figures a mida real i neons per tot el local. Porta el mòbil carregat.','Noren at the door, hand-painted murals, life-size figures and neon everywhere. Bring a charged phone.','Noren à l’entrée, fresques peintes à la main, figurines grandeur nature et néons partout. Venez avec un téléphone chargé.'],
['Noren y neones','Noren i neons','Noren & neon','Noren et néons'],['Así se vive HOKUSAI','Així es viu HOKUSAI','This is HOKUSAI','L’ambiance HOKUSAI'],['Murales y cerezos','Murals i cirerers','Murals & cherry blossoms','Fresques et cerisiers'],['Figuras a tamaño real','Figures a mida real','Life-size figures','Figurines grandeur nature'],['Ramen recién hecho','Ramen acabat de fer','Freshly made ramen','Ramen tout juste préparé'],['Farolillos y murales','Fanalets i murals','Lanterns & murals','Lanternes et fresques'],
['コエ · OPINIONES','コエ · OPINIONS','コエ · REVIEWS','コエ · AVIS'],['Lo que dicen','El que diuen','What people say','Ce qu’on dit'],['en Google','a Google','on Google','sur Google'],['1,1 mil reseñas · Ver en Google','1,1 mil ressenyes · Veure a Google','1.1K reviews · See on Google','1,1 k avis · Voir sur Google'],['DÉJANOS TU RESEÑA','DEIXA’NS LA TEVA RESSENYA','LEAVE US A REVIEW','LAISSEZ-NOUS UN AVIS'],
['Laura M. · Familia, Reus','Laura M. · Família, Reus','Laura M. · Family, Reus','Laura M. · Famille, Reus'],['James P. · Turista, UK','James P. · Turista, Regne Unit','James P. · Visitor, UK','James P. · Touriste, Royaume-Uni'],['Marc R. · Grupo, Tarragona','Marc R. · Grup, Tarragona','Marc R. · Group, Tarragona','Marc R. · Groupe, Tarragone'],['Camille D. · Turista, Francia','Camille D. · Turista, França','Camille D. · Visitor, France','Camille D. · Touriste, France'],
['パーティー · GRUPOS Y CUMPLES','パーティー · GRUPS I ANIVERSARIS','パーティー · GROUPS & BIRTHDAYS','パーティー · GROUPES ET ANNIVERSAIRES'],['¿Cumple?','Aniversari?','Birthday?','Un anniversaire ?'],['¡Aquí se celebra!','Aquí es celebra!','Celebrate it here!','On le fête ici !'],
['Trae a tus amigos, a la familia o al equipo entero. Cumpleaños, cenas de empresa, despedidas o el grupo del cosplay: juntamos mesas y os sentamos a todos juntos.','Porta els amics, la família o l’equip sencer. Aniversaris, sopars d’empresa, comiats o el grup del cosplay: ajuntem taules i us asseiem tots junts.','Bring your friends, family or the whole team. Birthdays, work dinners, parties or your cosplay crew: we push tables together so you all sit together.','Venez entre amis, en famille ou avec toute l’équipe. Anniversaires, dîners d’entreprise, EVJF ou votre groupe cosplay : on rapproche les tables pour vous réunir.'],
['Juntamos mesas para que estéis todos juntos','Ajuntem taules perquè estigueu tots junts','We join tables so you can all sit together','On rapproche les tables pour que vous soyez tous ensemble'],['Cuantos más, mejor: sin límite de personas','Com més serem, més riurem: sense límit de persones','The more the merrier: no group size limit','Plus on est de fous… : pas de limite de personnes'],['Precio especial para niños','Preu especial per a nens','Special price for kids','Tarif spécial enfants'],['Fotos de grupo con las figuras y los neones','Fotos de grup amb les figures i els neons','Group photos with the figures and neon','Photos de groupe avec les figurines et les néons'],
['PEDIR PRESUPUESTO','DEMANAR PRESSUPOST','ASK FOR A QUOTE','DEMANDER UN DEVIS'],['RESERVAR ONLINE','RESERVAR EN LÍNIA','BOOK ONLINE','RÉSERVER EN LIGNE'],
['アクセス · UBICACIÓN Y HORARIO','アクセス · UBICACIÓ I HORARI','アクセス · LOCATION & HOURS','アクセス · ACCÈS ET HORAIRES'],['Te esperamos','T’esperem','See you','On vous attend'],['en Salou','a Salou','in Salou','à Salou'],['Todos los días','Cada dia','Every day','Tous les jours'],
['En coche:','En cotxe:','By car:','En voiture :'],['zona azul en las calles de alrededor (Via Roma, Via Augusta, C. Barcelona). Puedes pagar desde el móvil con la app Aparcar de Salou.','zona blava als carrers del voltant (Via Roma, Via Augusta, C. Barcelona). Pots pagar des del mòbil amb l’app Aparcar de Salou.','paid street parking nearby (Via Roma, Via Augusta, C. Barcelona). Pay by phone with Salou’s Aparcar app.','stationnement payant dans les rues voisines (Via Roma, Via Augusta, C. Barcelona). Paiement par mobile avec l’app Aparcar de Salou.'],
['A pie:','A peu:','On foot:','À pied :'],['junto a la plaza del Carrilet (la de la locomotora), a unos minutos del paseo marítimo y el Club Nàutic.','al costat de la plaça del Carrilet (la de la locomotora), a uns minuts del passeig marítim i el Club Nàutic.','next to Plaça del Carrilet (the one with the old locomotive), a few minutes from the seafront and the Club Nàutic.','à côté de la place du Carrilet (celle de la locomotive), à quelques minutes du front de mer et du Club Nàutic.'],
['En bus:','En bus:','By bus:','En bus :'],['paradas Ciutat de Reus – Via Roma (2 min a pie) y Barcelona – Via Augusta (3 min).','parades Ciutat de Reus – Via Roma (2 min a peu) i Barcelona – Via Augusta (3 min).','stops Ciutat de Reus – Via Roma (2 min walk) and Barcelona – Via Augusta (3 min).','arrêts Ciutat de Reus – Via Roma (2 min à pied) et Barcelona – Via Augusta (3 min).'],
['En tren:','En tren:','By train:','En train :'],['estación Salou–PortAventura, a unos 2 km (taxi o bus).','estació Salou–PortAventura, a uns 2 km (taxi o bus).','Salou–PortAventura station, about 2 km away (taxi or bus).','gare Salou–PortAventura, à environ 2 km (taxi ou bus).'],['CÓMO LLEGAR','COM ARRIBAR-HI','GET DIRECTIONS','ITINÉRAIRE'],
['姉妹店 · NUESTRO OTRO LOCAL','姉妹店 · EL NOSTRE ALTRE LOCAL','姉妹店 · OUR OTHER RESTAURANT','姉妹店 · NOTRE AUTRE RESTAURANT'],['Pequeños placeres, grandes momentos.','Petits plaers, grans moments.','Small pleasures, big moments.','Petits plaisirs, grands moments.'],
['Restaurante japonés, sushi bar y take away en el centro de Salou. Mismo equipo, otro ambiente: más tranquilo, con jardín colgante y luz cálida.','Restaurant japonès, sushi bar i take away al centre de Salou. Mateix equip, un altre ambient: més tranquil, amb jardí penjant i llum càlida.','Japanese restaurant, sushi bar and takeaway in central Salou. Same team, different vibe: calmer, with a hanging garden and warm light.','Restaurant japonais, bar à sushis et vente à emporter au centre de Salou. Même équipe, autre ambiance : plus calme, avec jardin suspendu et lumière chaleureuse.'],
['VISITAR HANAKISALOU.COM','VISITAR HANAKISALOU.COM','VISIT HANAKISALOU.COM','VISITER HANAKISALOU.COM'],
['ヨヤク · RESERVA','ヨヤク · RESERVA','ヨヤク · BOOKING','ヨヤク · RÉSERVATION'],['Reserva','Reserva','Book','Réservez'],['tu mesa','la teva taula','your table','votre table'],
['En verano y fines de semana se llena. Rellena el formulario y te abrimos WhatsApp con el mensaje listo para enviar.','A l’estiu i els caps de setmana s’omple. Omple el formulari i t’obrim WhatsApp amb el missatge a punt per enviar.','It fills up in summer and at weekends. Fill in the form and we’ll open WhatsApp with your message ready to send.','C’est complet l’été et le week-end. Remplissez le formulaire et on ouvre WhatsApp avec votre message prêt à envoyer.'],
['RESERVAR POR WHATSAPP','RESERVAR PER WHATSAPP','BOOK ON WHATSAPP','RÉSERVER PAR WHATSAPP'],['O llámanos:','O truca’ns:','Or call us:','Ou appelez-nous :'],['Nombre','Nom','Name','Nom'],['Fecha','Data','Date','Date'],['Hora','Hora','Time','Heure'],['Elige','Tria','Choose','Choisir'],['Personas','Persones','Guests','Personnes'],['Teléfono','Telèfon','Phone','Téléphone'],
['SOLICITAR RESERVA','SOL·LICITAR RESERVA','REQUEST BOOKING','DEMANDER LA RÉSERVATION'],['Al enviar aceptas la','En enviar acceptes la','By sending you accept the','En envoyant, vous acceptez la'],['política de privacidad','política de privacitat','privacy policy','politique de confidentialité'],
['¡Casi listo!','Gairebé a punt!','Almost done!','Presque fini !'],['Te hemos abierto WhatsApp con tu reserva escrita. Solo falta darle a enviar.','T’hem obert WhatsApp amb la reserva escrita. Només cal que li donis a enviar.','We’ve opened WhatsApp with your booking written out. Just hit send.','WhatsApp est ouvert avec votre réservation rédigée. Il ne reste qu’à envoyer.'],['Hacer otra reserva','Fer una altra reserva','Make another booking','Faire une autre réservation'],
['Sushi buffet libre en Salou. Restaurante japonés con temática anime en la Costa Daurada.','Sushi bufet lliure a Salou. Restaurant japonès temàtic d’anime a la Costa Daurada.','All-you-can-eat sushi in Salou. Anime-themed Japanese restaurant on the Costa Daurada.','Sushi à volonté à Salou. Restaurant japonais sur le thème de l’anime sur la Costa Daurada.'],
['SÍGUENOS','SEGUEIX-NOS','FOLLOW US','SUIVEZ-NOUS'],['Carta de alérgenos','Carta d’al·lèrgens','Allergen menu','Carte des allergènes'],['Aviso legal','Avís legal','Legal notice','Mentions légales'],['Política de privacidad','Política de privacitat','Privacy policy','Politique de confidentialité'],['Política de cookies','Política de galetes','Cookie policy','Politique de cookies'],['IDIOMA','IDIOMA','LANGUAGE','LANGUE'],
['© 2026 HOKUSAI Sushi · Buffet Libre · Salou, Tarragona. Ilustraciones y grafismo originales.','© 2026 HOKUSAI Sushi · Bufet Lliure · Salou, Tarragona.','© 2026 HOKUSAI Sushi · All You Can Eat · Salou, Tarragona.','© 2026 HOKUSAI Sushi · Buffet à volonté · Salou, Tarragone.'],
['VOLVER','TORNAR','BACK','RETOUR'],
['@Tu nombre','El teu nom','Your name','Votre nom'],['@Cambiar idioma','Canviar idioma','Change language','Changer de langue'],['@Reservar por WhatsApp','Reservar per WhatsApp','Book on WhatsApp','Réserver par WhatsApp']
];
const IDX = { CA: 1, EN: 2, FR: 3 };
const TXT = new Map(), ATT = new Map();
for (const r of T) (r[0][0] === '@' ? ATT : TXT).set(r[0].replace(/^@/, ''), r);
const norm = s => s.replace(/\s+/g, ' ').trim();

export function applyLang(root, lang) {
  const i = IDX[lang] || 0;
  document.documentElement.lang = (lang || 'ES').toLowerCase();
  const w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let n;
  while ((n = w.nextNode())) {
    if (n.__tr === undefined || n.nodeValue !== n.__tr) n.__es = n.nodeValue;
    const key = norm(n.__es); if (!key) continue;
    const r = TXT.get(key);
    const out = i && r ? n.__es.replace(key, r[i]) : n.__es;
    if (n.nodeValue !== out) n.nodeValue = out;
    n.__tr = out;
  }
  root.querySelectorAll('[placeholder],[aria-label]').forEach(el => ['placeholder', 'aria-label'].forEach(a => {
    const v = el.getAttribute(a); if (v == null) return;
    const st = (el.__i18n = el.__i18n || {});
    if (st[a] === undefined || v !== st[a].tr) st[a] = { es: v };
    const r = ATT.get(st[a].es); const out = i && r ? r[i] : st[a].es;
    if (v !== out) el.setAttribute(a, out);
    st[a].tr = out;
  }));
}

export function watchLang(getLang) {
  let raf = 0, busy = false;
  const run = () => { raf = 0; busy = true; applyLang(document.body, getLang()); mo.takeRecords(); busy = false; };
  const mo = new MutationObserver(() => { if (!busy && !raf) raf = requestAnimationFrame(run); });
  mo.observe(document.body, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ['placeholder', 'aria-label'] });
  run();
  return { refresh: run, stop: () => mo.disconnect() };
}
